### ISSUE TITLE
Support Dynamic framework

### ISSUE THREAD

**Issue by cincas** [brightcove/brightcove-player-sdk-ios-ima#4]
Hi there,

Just curious about supporting dynamic framework.
Currently, we are developing a private pod which integrates with Brightcove player and IMA plugin.
But the problem for that is current IMA plugin (version 2.2.4) does not support dynamic framework, which I understand it was caused by Google IMA SDK.
Since Google has released few new versions (3.4 and above), and it does support dynamic framework now, we wonder when will you guys do a release to make this world "dynamic".

Thanks.

**Comment by timothyrodgers** [comment]
Hi,

Sorry for not seeing this message sooner. We monitor our Develop Forum closely, but not issues posted to github. Hopefully by now, your problem has long been resolved. The Brightcove plugin for IMA is only dynamic.

https://groups.google.com/forum/#!forum/brightcove-native-player-sdks

Thanks,
Tim
