### ISSUE TITLE
IMAAdDisplayContainer issue after updating sdks to 6.7.10

### ISSUE THREAD

**Issue by Venkata-Maniteja** [brightcove/brightcove-player-sdk-ios-ima#6]
In my project, I'm using Brightcove (player, ssai, ima) sdk and googleIMA sdk

After updating the brightcove sdks to 6.7.10 and google ima sdk to 3.12.1

I'm having issue with the IMAAdDisplayContainer related code. 

I never used "IMAAdDisplayContainer" in my project. I believe it is used internally by brightcove. 

After updating, the app crashes with the reason:

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**-[IMAAdDisplayContainer initWithAdContainer:companionSlots:]:** unrecognized selector sent to instance`

This is the old working code which broke after the sdk update:

        // Use the VMAP ads policy.
        BCOVIMAAdsRequestPolicy *adsRequestPolicy = [BCOVIMAAdsRequestPolicy videoPropertiesVMAPAdTagUrlAdsRequestPolicy];

        // FairPlay is set as the upstream session provider when creating the IMA session provider.
        id<BCOVPlaybackSessionProvider> imaSessionProvider = [sdkManager createIMASessionProviderWithSettings:imaSettings
                                                                                             adsRenderingSettings:renderSettings
                                                                                                 adsRequestPolicy:adsRequestPolicy
																									  adContainer:self->_adContainerView
                                                                                                   companionSlots:nil
                                                                                          upstreamSessionProvider:fps];

	self->_playbackController = [sdkManager createPlaybackControllerWithSessionProvider:imaSessionProvider
                                                                                                       viewStrategy:[self createCustomViewStrategyWithFrame:frame]];

I think createIMASessionProviderWithSettings:imaSettings is trigerring the call to "initWithAdContainer:companionSlots" which doesn't exist  in the new googleIMA SDK.

**Comment by timothyrodgers** [comment]
Hi Venkata-Maniteja,

In the future, please post questions related to the Brightcove Native Player SDKs in the Developer Forum here: https://groups.google.com/g/brightcove-native-player-sdks

As you can see in the README for this git repository, the Brightcove Native Player SDK for iOS supports version 3.11.4 of the Google IMA SDK. Please try downgrading your IMA framework to 3.11.4.

https://github.com/brightcove/brightcove-player-sdk-ios-ima#installation

IHTH,
Tim

**Comment by Venkata-Maniteja** [comment]
Hi @timothyrodgers thanks for quick response. 

It seems that google ima isnt allowing to download specific version. 

I downloaded it from https://developers.google.com/interactive-media-ads/docs/sdks/ios/client-side/download

and I see no option to download previous released versions.

Can you please point me where I can get 3.11.4 ?

**Comment by timothyrodgers** [comment]
Hi Venkata-Maniteja,

These are the IMA frameworks which are supported by Brightcove Native Player SDK for iOS 6.7.10.

For iOS:
https://imasdk.googleapis.com/native/downloads/ima-ios-v3.11.4.zip

For tvOS:
https://imasdk.googleapis.com/native/downloads/ima-tvos-v4.2.3.zip

- Tim

**Comment by Venkata-Maniteja** [comment]
Thanks tim, I'll post any issues I come across in that group.
