### ISSUE TITLE
UI API called from background thread

### ISSUE THREAD

**Issue by timothyrodgers** [brightcove/brightcove-player-sdk-ios-ima#8]
idanb-giniapps -

The error you posted says that you are performing a UI operation on a non-main thread which is confirmed by the "Thread 58" line of the stack trace screenshot you sent. The UI operation appears to be part of IMA's IMAAdLoader dealloc - it's releasing the WKWebView used by the Learn More feature.

Make sure you are not retaining the playback session object (BCOVIMASession) - keep only a weak reference to it.

If you are releasing a Playback Controller, do so on the main thread.

From your pastebin.com post, it appears your app is performing other UI operations on non-main threads. All UI code must execute on the main thread.

IHTH

**Comment by idanb-giniapps** [comment]
It looks like there is a call to `-[UIView removeFromSuperview]` in the IMA Framework that should be dispatched to the main queue but currently is not.

Seeing as the name of the queue is `com.brightcove.kvomanager.serialQueue` and this is printed in the console: 

`Main Thread Checker: UI API called on a background thread: -[UIView removeFromSuperview]
PID: 6947, TID: 829344, Thread name: (none), Queue name: com.brightcove.kvomanager.serialQueue, QoS: 0`

**Comment by timothyrodgers** [comment]
@idanb-giniapps, while I do not believe there is any requirement to release Objective-C objects on the main thread and that therefore this is an IMA issue, the Main Thread Checker exception you experienced is resolved in Brightcove Player SDK release 6.8.6. IHTH.

**Comment by idanb-giniapps** [comment]
the crash seems to have been resolved. thanks you.
